In [1]:
import pandas as pd

In [10]:
data1 = {'Feature1': ['10', '20', 'Thirty'],
        'Feature2': [5.5, 6.7, 8.9]}

In [11]:
df = pd.DataFrame(data1)
df['Feature1'] = pd.to_numeric(df['Feature1'], errors='coerce')

In [8]:
print(df)

   Feature1  Feature2
0      10.0       5.5
1      20.0       6.7
2       NaN       8.9


In [12]:
data2 = {'A': [1, 2, None],
        'B': [4, None, 6]}

In [13]:
df = pd.DataFrame(data2)
df.fillna(df.mean(), inplace=True)

In [14]:
print(df)

     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [15]:
from sklearn.linear_model import LinearRegression
import numpy as np

In [16]:
X = np.array([[1], [2], [3], [4], [5]])  # Reshape X into 2D
y = np.array([2, 4, 6, 8, 10])

In [18]:
model = LinearRegression()
model.fit(X, y)



LinearRegression()

In [19]:
print(model.predict([[6]]))

[12.]


In [20]:
from sklearn.preprocessing import StandardScaler
import numpy as np

In [22]:
data3 = np.array([[10], [20], [30], [40], [50]])

In [23]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data3)

In [24]:
print(scaled_data)

[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1] 

In [27]:
model = LogisticRegression()
model.fit(X, y)

LogisticRegression()

In [28]:
print(model.predict([[4, 5]]))

[1]


In [32]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [33]:
df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

In [36]:
encoder = OneHotEncoder(sparse_output=False)
encoded = encoder.fit_transform(df[['Category']]) 
print(encoded)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [37]:
from sklearn.model_selection import train_test_split

In [38]:
X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0, 1] 

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print("X_train:", X_train)
print("y_train:", y_train)

X_train: [[7, 8], [3, 4], [5, 6]]
y_train: [1, 1, 0]


In [40]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

In [41]:
X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]


In [42]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)

In [43]:
model = LogisticRegression()
model.fit(X_train, y_train_encoded)

LogisticRegression()

In [44]:
print(model.predict([[2, 3]]))

[1]


In [56]:
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression

In [57]:
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

In [64]:
imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train)

In [70]:
model = LinearRegression()
model.fit(X_train_imputed, y_train_encoded)

LinearRegression()

In [71]:
prediction = model.predict([[3, 4]])
print("Predicted Output:", prediction)

Predicted Output: [1.]


In [72]:
from sklearn.preprocessing import LabelEncoder

In [76]:
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression

imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train)


model = LinearRegression()
model.fit(X_train_imputed, y_train_encoded)


print(model.predict(imputer.transform([[2, 3]])))



[0.5]


In [78]:
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
import numpy as np

preprocessor = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),  # Replace NaN with mean values
    ('scaler', StandardScaler())
])


X_train_processed = preprocessor.fit_transform(X_train)


model.fit(X_train_processed, y_train)


X_test = np.array([[1, 150]])
X_test_processed = preprocessor.transform(X_test)

# Make prediction
print(model.predict(X_test_processed))

[380.]
